[package]
name = "elastiql"
version = "0.1.0"
authors = ["William Myers <mwilliammyers@gmail.com>"]
edition = "2018"

[features]
default = ["builder"]

graphql = []
builder = ["typed-builder"]

[dependencies]
async-graphql = { version = "1.14.*" }
base64 = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
typed-builder = { version = "0.6", optional = true }
